from typing import Any, Callable


def connect(endpoint: str, *, protocol: str = ...) -> Any: ...
def disconnect(connection: Any) -> None: ...
def send_message(connection: Any, topic: str, payload: Any) -> None: ...
def receive_message(connection: Any, topic: str, *, timeout: float = ...) -> Any: ...
def subscribe(connection: Any, topic: str, callback: Callable[[Any], None]) -> Any: ...
def unsubscribe(subscription: Any) -> None: ...
def create_channel(connection: Any, name: str, *, buffer_size: int = ...) -> Any: ...
def get_connection_status(connection: Any) -> Any: ...
def broadcast(connection: Any, payload: Any) -> int: ...
def set_qos(connection: Any, *, level: int, retry_count: int = ...) -> None: ...
