from typing import Any

Vector3 = tuple[float, float, float]


class VehicleState:
    position: Any
    speed: float


class CollisionInfo:
    collided: bool
    other: Any


def init_simulator(*, host: str = ..., port: int = ...) -> Any: ...
def load_scene(path: str) -> Any: ...
def create_vehicle(vehicle_type: str, position: Vector3, *, color: str = ...) -> Any: ...
def add_sensor(
    vehicle: Any,
    sensor_type: str,
    *,
    position: Vector3 | None = ...,
    config: dict[str, Any] | None = ...,
) -> Any: ...
def init_sensor(vehicle: Any, sensor_type: str) -> Any: ...
def start_simulation(*, realtime: bool = ...) -> None: ...
def stop_simulation() -> None: ...
def step(*, delta_time: float = ...) -> Any: ...
def get_vehicle_state(vehicle: Any) -> VehicleState: ...
def set_vehicle_control(vehicle: Any, *, throttle: float, steer: float) -> None: ...
def get_sensor_data(sensor: Any) -> Any: ...
def set_weather(weather: str, *, intensity: float = ...) -> None: ...
def add_pedestrian(position: Vector3, *, target: Vector3 | None = ..., speed: float = ...) -> Any: ...
def destroy(instance: Any) -> None: ...
def get_collision_info(vehicle: Any) -> CollisionInfo: ...
